<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDf6Jxw4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDf6Jxw4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDf6Jxw4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDf6Jxw4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDf6Jxw4\App_KernelDevDebugContainer([
    'container.build_hash' => 'Df6Jxw4',
    'container.build_id' => '42c5303d',
    'container.build_time' => 1698998143,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDf6Jxw4');
